experiment_params:
  base_data_dir: "./data/swdpf/arff_folds"
  run_iter: 10                # Number of experiment iterations   50
  iteration: 4                # Co-training iterations            20
  tau: 3                      # Threshold per smearing            3
  gr: 1                       # Growth rate per iteration         1
  K: 3                        # K-nearest neighbors               3

dataset_params:
  scale_labeled_samples: [0.1, 0.2, 0.3]                # [0.005, .025, .05]
  dataset_path_fixed: "training_dataset"
  evaluation_path_fixed: "evaluation_dataset"
  dataset_path: "training_dataset"
  evaluation_path: "evaluation_dataset"

model_params:
  number_of_neurons_1: 16
  number_of_neurons_2: 32
  in_channels: 19
  number_pos_neg: 5

exp_params:
  batch_size: 256
  epochs: 30
  LR: 0.001
  optimizer: "adam"

logging_params:
  save_dir: "./saves/"
  manual_seed: 2333
